#!/bin/bash
thopJar=`ls thop*.jar`
lanternaJar=`ls lanterna*.jar`

# set this
toolsJar=$JAVA_HOME/lib/tools.jar
if [ ! -f $toolsJar ]; then
	toolsJar=/usr/lib/jvm/default/lib/tools.jar
	if [ ! -f $toolJar ]; then 
		toolsJar=/usr/lib/jvm/java/lib
		if [ ! -f $toolsJar ]; then
		    echo "tools.jar not found, your JAVA_HOME must point to a JDK not a JRE"
		    exit 1			
		fi
	fi
fi

java -cp $thopJar:$lanternaJar:$toolsJar com.ds.thop.Thop $1
